name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Setup:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Go to Work directory
      run: cd /home/bitnami/htdocs/ci-ci-php/

  Cleanup:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: cleanp-directory
      run: git reset --hard

  Deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Pull latest code
      run: git pull origin main


