name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  Cleanup:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: cleanp-directory
      run: cd /home/bitnami/htdocs/ci-ci-php/ && git reset --hard

  Deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Pull latest code
      run: cd /home/bitnami/htdocs/ci-ci-php/ &&  git pull origin main


